services:
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: builder
      args:
        - BUILD_ENV=dev
    env_file:
      - ./env/.env.shared
      - ./env/.env.api
    command: ["sh", "-c", "air -d"]
    volumes:
      - .:/go/src/myblog
    working_dir: /go/src/myblog
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - rdb
    extra_hosts:
      - host.docker.internal:host-gateway

  batch:
    build:
      context: .
      dockerfile: ./docker/batch/Dockerfile
      target: builder
    env_file:
      - ./env/.env.shared
      - ./env/.env.batch
    volumes:
      - .:/go/src/myblog
    working_dir: /go/src/myblog
    depends_on:
      - rdb
    extra_hosts:
      - host.docker.internal:host-gateway

  rdb:
    image: mysql:8.0.34
    platform: linux/amd64
    ports:
      - "3306:3306"
    env_file:
      - ./env/.env.shared
      - ./env/.env.db
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    restart: on-failure

  rdb-test:
    image: mysql:8.0.34
    platform: linux/amd64
    ports:
      - "3307:3306"
    env_file:
      - ./env/.env.shared
      - ./env/.env.db
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    restart: on-failure
